# NixOS module for CVMFS with systemd automount.
#
# Nix concept: A NixOS *module* is a function that takes { config, lib, pkgs, ... }
# and returns an attribute set with two keys:
#
#   options  — declares what settings users can configure (the "interface")
#   config   — implements those settings by generating files, services, etc.
#
# When you write `services.cvmfs.enable = true` in your configuration.nix,
# NixOS's module system finds this module, evaluates the `config` section,
# and merges the result into your system configuration.
#
# The `lib.mkIf cfg.enable { ... }` pattern means: only apply this config
# when the user has set `services.cvmfs.enable = true`.

{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.cvmfs;

  # Generate the content of /etc/cvmfs/default.local from module options.
  # This file overrides CVMFS defaults with user-specified values.
  defaultLocalConf = lib.concatStringsSep "\n" (
    [ "# Generated by NixOS — do not edit manually" ]
    ++ lib.optional (cfg.repositories != [ ]) "CVMFS_REPOSITORIES=${lib.concatStringsSep "," cfg.repositories}"
    ++ lib.optional (cfg.httpProxy != null) "CVMFS_HTTP_PROXY='${cfg.httpProxy}'"
    ++ lib.optional (cfg.quotaLimit != null) "CVMFS_QUOTA_LIMIT=${toString cfg.quotaLimit}"
    ++ lib.optional (cfg.cacheBase != null) "CVMFS_CACHE_BASE=${cfg.cacheBase}"
    ++ lib.optional (cfg.clientProfile != null) "CVMFS_CLIENT_PROFILE=${cfg.clientProfile}"
    ++ lib.mapAttrsToList (k: v: "${k}=${v}") cfg.extraConfig
    ++ [ "" ] # trailing newline
  );

  # Merge the package's config.d/ directory with user-provided per-repo configs.
  #
  # Nix concept: `pkgs.runCommand` creates a derivation that runs a shell script.
  # We use it to build a merged directory in the Nix store combining:
  #   - Default per-repo configs from the CVMFS package
  #   - User-provided .local overrides from the module options
  configDDir = pkgs.runCommand "cvmfs-config-d" { } ''
    mkdir -p $out
    # Copy package defaults (may not exist for all repos)
    if [ -d "${cfg.package}/etc/cvmfs/config.d" ]; then
      cp -r ${cfg.package}/etc/cvmfs/config.d/* $out/ 2>/dev/null || true
    fi
    # Add user-provided per-repo configs
    ${lib.concatStringsSep "\n" (
      lib.mapAttrsToList (
        repo: content:
        "cat > $out/${lib.escapeShellArg repo}.local << 'CVMFSEOF'\n${content}\nCVMFSEOF"
      ) cfg.extraRepoConfig
    )}
  '';

  # Helper: the mountpoint path for a repository
  repoMountPoint = repo: "/cvmfs/${repo}";
in
{
  # ─── Options ──────────────────────────────────────────────────────────
  #
  # These define what the user can configure. Each option has a type
  # (for validation), a default, and a description.
  # `lib.mkEnableOption` is shorthand for a boolean option defaulting to false.

  options.services.cvmfs = {
    enable = lib.mkEnableOption "CernVM-FS client with systemd automount";

    package = lib.mkOption {
      type = lib.types.package;
      description = "The CVMFS package to use.";
    };

    repositories = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [
        "sft.cern.ch"
        "cms.cern.ch"
        "cvmfs-config.cern.ch"
      ];
      description = ''
        List of CVMFS repository fully-qualified names to automount.
        Each gets a systemd .mount and .automount unit at /cvmfs/<repo>.
      '';
    };

    httpProxy = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "DIRECT";
      example = "http://squid.example.com:3128";
      description = ''
        HTTP proxy for CVMFS.
        - "DIRECT": no proxy, connect to Stratum 1 servers directly.
        - "auto": use WPAD (Web Proxy Auto-Discovery).
        - A URL like "http://proxy:3128": use that proxy.
        Set to null to omit (CVMFS default requires a proxy unless
        clientProfile is "single").
      '';
    };

    quotaLimit = lib.mkOption {
      type = lib.types.nullOr lib.types.int;
      default = 4000;
      description = "Soft limit in MB for the local CVMFS cache.";
    };

    cacheBase = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "/var/cache/cvmfs";
      description = "Base directory for the CVMFS local cache.";
    };

    clientProfile = lib.mkOption {
      type = lib.types.nullOr (lib.types.enum [ "single" ]);
      default = "single";
      description = ''
        Client profile. "single" is appropriate for laptops and single-user
        machines — it enables automatic proxy discovery via WPAD and relaxes
        some timeout settings. Set to null for cluster deployments with a
        dedicated Squid proxy.
      '';
    };

    extraConfig = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = {
        CVMFS_TIMEOUT = "10";
        CVMFS_NFILES = "65536";
      };
      description = "Additional key-value pairs appended to default.local.";
    };

    extraRepoConfig = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = {
        "atlas.cern.ch" = "CVMFS_QUOTA_LIMIT=8000";
      };
      description = ''
        Per-repository configuration overrides.
        Keys are repository FQRNs, values are the content for
        /etc/cvmfs/config.d/<repo>.local.
      '';
    };

    automountIdleTimeout = lib.mkOption {
      type = lib.types.str;
      default = "600";
      description = ''
        Seconds of inactivity after which systemd unmounts the CVMFS
        filesystem. Set to "0" to keep it mounted indefinitely.
      '';
    };

    unmountOnSuspend = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Unmount all CVMFS repositories before the system suspends or
        hibernates.

        Long-lived CVMFS connections do not survive a laptop sleep cleanly,
        especially when the resume crosses a network change or a stratum-1
        failover. Stale FUSE handles then cause any process touching
        /cvmfs/* to block forever in fuse_send_open, which on a desktop
        session prevents systemd from freezing user.slice and can push
        GNOME into a screen-blank auto-suspend loop.

        Set to false on always-on hosts where unmounting is needless churn.
      '';
    };
  };

  # ─── Config ───────────────────────────────────────────────────────────
  #
  # This section implements the options above. It only takes effect when
  # `services.cvmfs.enable` is true (that's what `lib.mkIf` does).

  config = lib.mkIf cfg.enable {

    # ── Packages ──
    # Make cvmfs2, cvmfs_config, etc. available system-wide.
    environment.systemPackages = [ cfg.package ];

    # Register the mount helper so systemd can find mount.cvmfs / mount.fuse.cvmfs2.
    #
    # Nix concept: `system.fsPackages` tells NixOS "these packages provide
    # filesystem mount helpers". NixOS adds them to the system PATH so that
    # `mount -t fuse.cvmfs2` works (it needs to find `mount.fuse.cvmfs2`).
    system.fsPackages = [ cfg.package ];

    # ── Kernel module ──
    # CVMFS uses FUSE, which needs the `fuse` kernel module loaded.
    boot.kernelModules = [ "fuse" ];

    # ── Service user ──
    # CVMFS drops privileges to this user when running the FUSE process.
    # default.conf sets CVMFS_USER=cvmfs (read-only), so we must create it.
    users.groups.cvmfs = { };
    users.users.cvmfs = {
      isSystemUser = true;
      group = "cvmfs";
      description = "CernVM-FS service user";
    };

    # ── FUSE configuration ──
    # allow_other lets non-root users access FUSE mounts (needed for shared /cvmfs).
    programs.fuse.userAllowOther = true;

    # ── Configuration files ──
    #
    # Nix concept: `environment.etc` creates managed symlinks in /etc/.
    # Each entry becomes /etc/<name> pointing to a file in the Nix store.
    # This is how NixOS populates /etc without needing a writable filesystem.
    # On the next `nixos-rebuild switch`, old symlinks are replaced atomically.
    environment.etc = {
      # Package-provided default config
      "cvmfs/default.conf".source = "${cfg.package}/etc/cvmfs/default.conf";

      # Distribution default snippets (e.g. 50-cern.conf)
      "cvmfs/default.d".source = "${cfg.package}/etc/cvmfs/default.d";

      # Domain configs from the package (cern.ch.conf, etc.)
      "cvmfs/domain.d".source = "${cfg.package}/etc/cvmfs/domain.d";

      # Per-repo configs — merged from package defaults + user overrides
      "cvmfs/config.d".source = configDDir;

      # Public keys for signature verification (CERN, EGI, OSG)
      "cvmfs/keys".source = "${cfg.package}/etc/cvmfs/keys";

      # User-local overrides — generated from this module's options
      "cvmfs/default.local".text = defaultLocalConf;
    };

    # ── Directories ──
    # Create cache and mountpoint directories.
    #
    # Nix concept: `systemd.tmpfiles.rules` uses systemd-tmpfiles to create
    # directories at boot. The format is: "type path mode user group age"
    # "d" = create directory if it doesn't exist.
    systemd.tmpfiles.rules =
      [
        "d ${cfg.cacheBase} 0755 cvmfs cvmfs -"
        "d /cvmfs 0755 root root -"
      ]
      ++ map (repo: "d ${repoMountPoint repo} 0755 root root -") cfg.repositories;

    # ── Systemd mount units ──
    #
    # One .mount unit per repository. These are triggered by the automount
    # units below — they don't start on their own (wantedBy is empty).
    #
    # Nix concept: `systemd.mounts` is a NixOS option that generates
    # systemd .mount unit files. The unit name is derived from the `where`
    # path (e.g., /cvmfs/sft.cern.ch → cvmfs-sft.cern.ch.mount).
    systemd.mounts = map (repo: {
      what = repo;
      where = repoMountPoint repo;
      type = "fuse.cvmfs2";
      options = lib.concatStringsSep "," [
        "allow_other"
        "grab_mountpoint"
      ];

      # Don't start automatically — the automount unit triggers us
      wantedBy = [ ];

      # Wait for network before mounting (CVMFS needs HTTP access)
      requires = [ "network-online.target" ];
      after = [ "network-online.target" ];

      mountConfig = {
        TimeoutSec = "60";
        LazyUnmount = true;
      };
    }) cfg.repositories;

    # ── Systemd automount units ──
    #
    # One .automount unit per repository. These listen on /cvmfs/<repo> and
    # trigger the corresponding .mount unit on first access.
    #
    # How it works: systemd creates /cvmfs/<repo> as an automount point.
    # When any process tries to `ls /cvmfs/sft.cern.ch/`, the kernel triggers
    # the automount, systemd starts the .mount unit (which runs mount.cvmfs),
    # and CVMFS mounts the repository via FUSE. After `TimeoutIdleSec` seconds
    # of no file access, systemd unmounts it automatically.
    systemd.automounts = map (repo: {
      where = repoMountPoint repo;

      # Start automount listeners at boot (remote-fs.target is the standard
      # target for network filesystems).
      wantedBy = [ "remote-fs.target" ];

      automountConfig = {
        TimeoutIdleSec = cfg.automountIdleTimeout;
      };
    }) cfg.repositories;

    # ── Pre-suspend unmount hook ──
    #
    # Ordered before sleep.target so cvmfs_config umount runs as part of
    # the transition into any sleep mode (suspend / hibernate / hybrid /
    # suspend-then-hibernate). The .automount units stay armed and
    # re-trigger a fresh mount on first /cvmfs/* access after resume, so
    # there is no symmetric "remount on resume" hook to install.
    #
    # If cvmfs_config umount itself wedges (a process is holding a mount
    # open in D-state), TimeoutStartSec aborts it and the suspend
    # transition fails — preferable to entering sleep with stale state.
    systemd.services.cvmfs-umount-on-suspend = lib.mkIf cfg.unmountOnSuspend {
      description = "Unmount CVMFS repositories before sleep";
      before = [ "sleep.target" ];
      wantedBy = [ "sleep.target" ];
      # cvmfs_config umount shells out to bare-name tools that aren't in the
      # default systemd service PATH: `mount`/`umount`/`fuser` (util-linux)
      # and `awk` (gawk). Without them the hook fails and suspend stalls.
      path = [
        pkgs.util-linux
        pkgs.gawk
      ];
      unitConfig.StopWhenUnneeded = true;
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        TimeoutStartSec = "30";
        ExecStart = "${cfg.package}/bin/cvmfs_config umount";
      };
    };
  };
}
